# Generated by Django 5.1.7 on 2025-07-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_activate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="recommend",
            field=models.BooleanField(default=True),
        ),
    ]
