# Generated by Django 5.1.7 on 2025-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_user_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("pub", "Published"), ("drf", "Draft")],
                default="drf",
                max_length=3,
            ),
        ),
    ]
